#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
server {
    listen      80;
    server_name "";
    
    location / {

        return 200 'Hello World!';
    }
    return 'Hello World!';
}
sudo service nginx restart